parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    MyBudget\Shared\:
        resource: '%kernel.project_dir%/src/Shared/'
        exclude:
            - '%kernel.project_dir%/src/Shared/Infrastructure/Symfony/Kernel.php'
    
