api_platform:
    title: MyBudget API
    version: 0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Budget/Infrastructure/ApiPlatform/Resource']
    # Mercure integration, remove if unwanted
    mercure: ~
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
