services:
    # private removed services have to be set public for tests
    # services becomes removed from the container if they are not used 
    # clear below list after expanding the app
    'MyBudget\Budget\Infrastructure\Repository\MemoryBudgetRepository':
        public: true
        
    'MyBudget\Budget\Infrastructure\Repository\DoctrineBudgetRepository':
        public: true
